### PR TITLE
Support multiple categories per product

### PR DESCRIPTION
**Pull request by omesser**
Adding support for multiple categories, and utilizing them in some projects (iguazio,mlrun)

Closes https://github.com/aporia-ai/mlops.toys/issues/15

### CODE REVIEW

**Comment by SnirShechter** [comment]
Closes #15

**Comment by omesser** [comment]
@SnirShechter soft ping

**Comment by SnirShechter** [comment]
@omesser 
Hey,

The code looks fine.

Regarding the multiple categories in projects: I don't think it's fair to add a project to so many categories. After further discussion, we've thought of a non-biased way to accomplish this:
* All projects can have up to **3 categories**
* An **All-In-One** category will be added to all-around projects/platforms

WDYT?

**Comment by omesser** [comment]
Hi @SnirShechter 
> "I don't think it's fair to add a project to so many categories"

I actually respectfully disagree 😄 
I have to admit I don't fully see how fairness (in the sense of category-per-product ratio) comes to play here. If a product lays in a certain category, then it just... does, it's not correct to say it doesn't because it lays in more than 2 others.

I think that when a user filters by a specific category they should see all products which answer this category (including the "wider" platforms/all-in-ones). Hence, for the discoverability of products (like Iguazio/MLRun or any other platform/"wide"-product) we would obviously want them to show up on the relevant categories and not only (maybe additionally) when people search for "all-in-one" - which I guess they seldom will.

The proposed solution would harm correctness of the discoverability criteria, in name of fairness - though exposure by category shouldn't aspire to be fair in this sense IMO.
This is ultimately not my decision to make, of course, but I think the categories here should be akin to descriptive labels - to allow correct label matching, the relevant labels should be attached to the resource directly, indirection via "special-meaning" labels is not ideal for user experience

I will fix this according to whatever you guys decide, but please consider the above

**Comment by SnirShechter** [comment]
@alongubkin @yanivzoh 
What do you think?

**Comment by alongubkin** [comment]
Hey @omesser!

Thank you so much for your contribution, I highly appreciate it! 

We built MLOps.toys after talking to users that wanted to build a modular ML platform, specialized for their needs, choosing small solutions to each one of their problems. Similarly to how you choose Git for version control, CircleCI for CI/CD, etc.

However, we definitely did not take into account the proper representation of end-to-end ML solutions, such as yours. 
We think that allowing up to 3 categories per product and adding a new category for end-to-end ML solutions would be the best fit for the community right now. 

Thank you!

**Comment by omesser** [comment]
@alongubkin  - Understood
So, I'll make the following changes:
- Adding "End to End" (Or "All In One" ?) Please choose the terminology (@alongubkin  @SnirShechter)
- Adding some enforcement so no project can list more than 3
- Changing current projects to use max 3 of course

**Comment by SnirShechter** [comment]
Hey @omesser ,
**1+3.** IMO "All-In-One" sounds good. If you're changing the current projects to use 3 categories instead of the All-In-One, the category does not need adding.
**2.** We'd appreciate the contribution, but I think it'll be easier to enforce that manually in the PR level, for the time being, until we put up tests for the content. You're welcome to add it to the README.md

**Comment by omesser** [comment]
@SnirShechter @alongubkin  - Hey folks
I apologize for not being available to close this loose end sooner.
PR is ready for review/merge (Added a small snippet in the README.md with guideline asking for a max of 3 categories to your request)

Thanks

**Comment by omesser** [comment]
@SnirShechter @alongubkin 
ping

**Comment by omesser** [comment]
Hi @SnirShechter 
Please take a look now, made some minor changes.
Please note I'm not a frontend guy... I'm using `<table>` / etc only because:
1. This is what you're using in the similar `worksWellWith` / `competesWith` code
2. These all look the same to me and this just seems to work and look good

If you want me to use another directive/class - please comment a code suggestion
Thanks!

**Comment by omesser** [comment]
ping @SnirShechter
it would be great to close this already :)
While this is open people just keep adding projects with the old `category` and not the new `categories` property

**Comment by omesser** [comment]
@SnirShechter @alongubkin ping :]
Can someone please take a look at this and either followup or just implement an alternative? I think support of multiple categories is sorely missing here and is pretty straightforward...
Thanks

**Comment by omesser** [comment]
I'm not getting any maintainer attention here... 🙁 
I suppose this is not a priority at this time so closing this

**Pull request closed without merging**
