### PR TITLE
Updating MLRun and Iguazio

### PR DESCRIPTION
**Pull request by alexiguazio**
Updating the categories for mlrun and iguazio, as well a few content changes.

### CODE REVIEW

**Comment by SnirShechter** [comment]
@alexiguazio 
Hey, 

I can't see Iguazio in the preview. Can you check everything is fine in the YAML?

**Comment by omesser** [comment]
@alexiguazio @SnirShechter Please note that https://github.com/aporia-ai/mlops.toys/pull/38 there are conflicting changes (added multiple categories to mlrun/iguazio)

**Comment by SnirShechter** [comment]
@omesser 
Hey, I saw but I suppose we better resolve the conflicts in #38 since this is just text changes.

I'm approving this.

**Comment by omesser** [comment]
@SnirShechter np resolved it on https://github.com/aporia-ai/mlops.toys/pull/38

**Pull request merged**
