### PR TITLE
Adds Ploomber

### PR DESCRIPTION
**Pull request by edublancas**
Please add [Ploomber](https://github.com/ploomber/ploomber) :)

### CODE REVIEW

**Comment by alongubkin** [comment]
I'm getting a YAML exception, can you please run this manually using `npm run dev` and make sure it works?

**Comment by edublancas** [comment]
There was a duplicated key, I think that was the problem.

I couldn't run `npm run dev`, I ran into issues when setting up the project. Tried with a local node installation and using the node Docker image. Let's hope it's already fixed, if it's not, I'll try to configure the project again. What's the setup process like? (I don't know much about node). I tried:

```sh
# this fails
npm install

npm run dev
```

**Comment by edublancas** [comment]
Looks like it's working now, I'm able to see the preview :)

**Comment by SnirShechter** [comment]
Hey @edublancas , 

The branch has conflicts, can you rebase?

**Comment by edublancas** [comment]
Just did!

**Comment by SnirShechter** [comment]
@edublancas 
Hey, there were too many conflicts so I just opened a new PR myself and merged it, I hope it's ok.

**Comment by SnirShechter** [comment]
Closed in favor of #32

**Comment by edublancas** [comment]
Sure, thanks a lot!

**Pull request closed without merging**
