### PR TITLE
Adding Open Vino Model Server

### PR DESCRIPTION
**Pull request by rasapala**
Adding Open Vino Model Server information.

### CODE REVIEW

**Comment by rasapala** [comment]
@dleybz @yonbek @skogstrom @alongubkin Please review the commit and push to the repository.

**Comment by rasapala** [comment]
@SnirShechter @alexiguazio @ncilfone @omesser @jsnctl Hi guys can you review and push the commit ?

**Comment by SnirShechter** [comment]
@rasapala 
Hey,

Sorry, I totally missed that PR. I will review it on Sunday.

Thanks!

**Comment by omesser** [comment]
I forgot about that too, I'll update it according to what was asked and ping

**Review by SnirShechter — APPROVED** [review]

**Pull request merged**
