### PR TITLE
Add Katonic.ai to Projects

### LINKED ISSUE #20: Please add Katonic.ai.

### PR DESCRIPTION
**Pull request by shourysharma**
# Description
This PR is for introduction of Katonic.ai into list of projects under MLOps Toys. Changes are welcome. Katonic.ai helps data scientists, data engineers and developers to quickly build, deploy and manage machine learning from research to production.

## Software Description
The platform is based on the popular Kubeflow framework, bringing together its powerful components and enhancing them with Entity Resolution and Automated Feature Engineering. Integrates with widely used ML and AI Libraries to experiment and create models with them. Katonic’s patented technology fully automates feature engineering, which is typically the most challenging and time-consuming part of data science.

## Type of change

- [ ] Added Katonic.ai in projects.yaml
- [ ] Added Katonic logo in project's static files

# How Has This Been Tested?
 

- [ ] Test A -  Windows
- [ ] Test B - Arch Linux

Closes #20

### CODE REVIEW

**Comment by alongubkin** [comment]
We prefer not to add a new "MLOps Platform" category, all categories are actually part of "MLOps Platform" :)

Also, the description should be more to the point of what your product actually does.

**Comment by shourysharma** [comment]
@alongubkin I have made the necessary changes as you mentioned. Looking forward for your review.

**Comment by SnirShechter** [comment]
@shourysharma 
I should also state that your description is purely marketing. The website intends to be informal and help people make decisions while reading the text you added does not actually make me understand it.

I suggest changing the text to something more informal - what it does, main features, advantages, etc.

**Comment by SnirShechter** [comment]
@shourysharma 
Awaiting your response.

**Comment by SnirShechter** [comment]
No response so I'm closing this. Feel free to reopen.

**Pull request closed without merging**
